name = "HydroModels"
uuid = "7e3cde01-c141-467b-bff6-5350a0af19fc"
version = "0.4.4"
authors = ["jingx <50790703+chooron@users.noreply.github.com>"]

[deps]
ComponentArrays = "b0b7db55-cfe3-40fc-9ded-d10e2dbeff66"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
HydroModelCore = "57609f06-44cb-4626-8f6d-47ea844d0af1"
Lux = "b2108857-7c20-44ae-9111-449ecde12c47"
NNlib = "872c559c-99b0-510c-b3b7-b6c96a88d5cd"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"

[weakdeps]
BasicModelInterface = "59605e27-edc0-445a-b93d-c09a3a50b330"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Optimization = "7f7a1694-90dd-40f0-9382-eb1efda571ba"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
SciMLBase = "0bca4576-84f4-4d90-8ffe-ffa030f20462"
SciMLSensitivity = "1ed8b502-d754-442c-8d5d-10ac956f44a1"

[extensions]
HydroModelsBMIExt = ["BasicModelInterface", "Dates"]
HydroModelsOptimizationExt = ["Optimization", "SciMLBase", "ComponentArrays"]
HydroModelsOrdinaryDiffEqExt = ["SciMLBase", "OrdinaryDiffEq", "SciMLSensitivity"]

[compat]
Aqua = "0.8"
BasicModelInterface = "0.1"
CSV = "0.10"
ComponentArrays = "0.15"
DataFrames = "1"
DataInterpolations = "8"
Dates = "1"
DocStringExtensions = "0.9"
Graphs = "1"
HydroModelCore = "0.2.4"
Lux = "1"
NNlib = "0.9"
Optimization = "4, 5"
OrdinaryDiffEq = "6"
Random = "1"
Reexport = "1"
SciMLBase = "2"
SciMLSensitivity = "7"
SpecialFunctions = "2"
StableRNGs = "1"
Statistics = "1"
Symbolics = "6,7"
TOML = "1"
Test = "1"
Zygote = "0.7"
julia = "1"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataInterpolations = "82cc6244-b520-54b8-b5a6-8a565e85f1d0"
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
SciMLSensitivity = "1ed8b502-d754-442c-8d5d-10ac956f44a1"
StableRNGs = "860ef19b-820b-49d6-a774-d7a799459cd3"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[targets]
test = ["Test", "Aqua", "CSV", "DataFrames", "Statistics", "StableRNGs", "DataInterpolations", "DifferentialEquations", "SciMLSensitivity", "Zygote"]
